version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: mr-cans-tyres-shop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mrcans_db}
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - mr-cans-tyres-shop-net

  redis:
    image: redis:7-alpine
    container_name: mr-cans-tyres-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis:/data
    restart: always
    networks:
      - mr-cans-tyres-shop-net

networks:
  mr-cans-tyres-shop-net:
    driver: bridge
