services:
  db:
    image: postgres:16-alpine
    container_name: canstyres-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-canstyres_db}
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - canstyres-net

  redis:
    image: redis:7-alpine
    container_name: canstyres-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis:/data
    restart: always
    networks:
      - canstyres-net

networks:
  canstyres-net:
    driver: bridge
